### PR TITLE
Feat/support fuse resend notify

### PR DESCRIPTION
**Pull request by xujihui1985**
The "Resend Notification" API is ready for integration into the upstream repository. Implement the resend function to facilitate easier failover implementation.

https://lore.kernel.org/all/20240109092443.519460-1-winters.zc@antgroup.com/T/

### CODE REVIEW

**Comment by aftersnow** [comment]
LGTM! Developers are suggested to check the 'FUSE_HAS_RESEND' feature flag in the fuse INIT request (by saving it to somewhere).

**Comment by xujihui1985** [comment]
fixed failed test for macOS, please help to run the ci again

**Comment by xujihui1985** [comment]
@imeoer I fixed clippy error to make ci happy, even through this not relate to my change. the ci is green on my forked branch, so please help to rerun the test again

**Comment by xujihui1985** [comment]
@bergwolf @imeoer could you proceed this PR, or anything need to be improved?

**Review by imeoer — APPROVED** [review]

**Pull request merged**
