### PR TITLE
abi: fix the conflict of PERFILE_DAX flag

### PR DESCRIPTION
**Pull request by mofishzz**
The current upstream flag is defined as:
FUSE_INIT_EXT (1 << 30)
FUSE_HAS_INODE_DAX (1ULL << 33)
We should follow it.

Signed-off-by: Huang Jianan <jnhuang@linux.alibaba.com>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]
lgtm!

**Comment by mofishzz** [comment]
It looks like clippy's error is from rust 1.67.0. 
The command "make check" works fine in my own rust 1.66.1 environment. 
Maybe I need to submit another PR to fix clippy's error first?

**Comment by bergwolf** [comment]
@mofishzz you can add another commit in this PR to address the clippy issues.

**Comment by mofishzz** [comment]
> @mofishzz you can add another commit in this PR to address the clippy issues.

updated

**Pull request merged**
