### PR TITLE
Add FD_PASSTHROUGH

### PR DESCRIPTION
**Pull request by yyyeerbo**

### CODE REVIEW

**Comment by jiangliu** [comment]
Is the `FD_PASSTHROUGH` defined by Linux kernel or a private flag? I can not find related definition in latest linux kernel header files.

**Comment by yyyeerbo** [comment]
> Is the `FD_PASSTHROUGH` defined by Linux kernel or a private flag? I can not find related definition in latest linux kernel header files.

It's a private flag used by antgroup

**Comment by bergwolf** [comment]
@jiangliu It's also available in the openanolis kernel.

**Comment by bergwolf** [comment]
replaced by #125

**Pull request closed without merging**
