### PR TITLE
linux_session: Make allow_other mount option optional

### PR DESCRIPTION
**Pull request by cbrewster**
The `allow_other` mount option typically requires root user permissions unless configured otherwise on the machine. It would be nice if this was configurable to allow for unprivileged mounting.

For non-root users to use this option the system must have 'user_allow_other' set in /etc/fuse.conf.

### CODE REVIEW

**Review by eryugey — APPROVED** [review]
LGTM

**Comment by flokli** [comment]
MacOS failures seem unrelated.

**Review by jiangliu — APPROVED** [review]

**Comment by jiangliu** [comment]
> MacOS failures seem unrelated.

Yes, it's independent of this PR and just get fixed.

**Comment by cbrewster** [comment]
> Yes, it's independent of this PR and just get fixed. Could you please help to rebase?

Done.

**Pull request merged**
