### PR TITLE
A few bugfixes

### PR DESCRIPTION
**Pull request by liubogithub**
This PR consists of several bug fixes regarding to fuse ops `readdirplus`.

### CODE REVIEW

**Comment by liubogithub** [comment]
It is weird that building fails, I did the same test locally, it ran fine.

The test is
```
clippy and format
      run: |
        cargo clippy --features "fusedev" -- -Dclippy::all
        cargo clippy --features "virtiofs" -- -Dclippy::all
        cargo clippy --features "vhost-user-fs" -- -Dclippy::all
        cargo fmt -- --check
```


```
root@6:/mnt/rust# cargo clippy --features "virtiofs" -- -Dclippy::all
    Updating crates.io index
    Updating git repository `https://github.com/cloud-hypervisor/vhost.git`
    Updating git repository `https://github.com/cloud-hypervisor/vm-virtio.git`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
  Downloaded cfg-if v0.1.10
  Downloaded bimap v0.4.0
  Downloaded libc v0.2.72
  Downloaded void v1.0.2
  Downloaded nix v0.17.0
  Downloaded vm-memory v0.2.1
  Downloaded arc-swap v0.4.7
  Downloaded log v0.4.6
  Downloaded vmm-sys-util v0.6.1
  Downloaded byteorder v1.2.1
  Downloaded bitflags v1.2.1
  Downloaded 11 crates (932.3 KB) in 0.63s
   Compiling libc v0.2.72
   Compiling bitflags v1.2.1
    Checking cfg-if v0.1.10
   Compiling nix v0.17.0
    Checking byteorder v1.2.1
    Checking void v1.0.2
    Checking arc-swap v0.4.7
    Checking log v0.4.6
    Checking bimap v0.4.0
    Checking vm-memory v0.2.1
    Checking vmm-sys-util v0.6.1
    Checking vm-virtio v0.1.0 (https://github.com/cloud-hypervisor/vm-virtio.git?branch=dragonball#2bf58c10)
    Checking fuse-rs v0.1.0 (/mnt/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 44.45s
```

**Comment by bergwolf** [comment]
@liubogithub Maybe rust version problem?

**Comment by liubogithub** [comment]
Looks like it's vm-memory version causing the trouble.

**Comment by jiangliu** [comment]
> Looks like it's vm-memory version causing the trouble.
> 
> So the problem is cause by the fact that vm-virtio needs a feature `integer-atomics` which is only available at vm-memory 0.2.1, but vm-memory 0.3 is pulled from crates.io.
> 
> Update:
> I've created a PR for vm-virtio dragonball branch to upgrade to vm-memory 0.3.0 [cloud-hypervisor/vm-virtio#4](https://github.com/cloud-hypervisor/vm-virtio/pull/4), once it gets merged, we'll be fine here.

Solved by this PR: https://github.com/cloud-hypervisor/vm-virtio/pull/6#event-4106284510

**Pull request closed without merging**
